---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- {name: boshrelease-ci}
- {name: boshrelease}
- {name: version}

outputs:
- {name: candidate-release}

run:
  path: ./boshrelease-ci/ci/tasks/create-candidate-release.sh
