---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease-ci

params:
  bosh_target:
  bosh_username: admin
  bosh_password: admin


run:
  path: boshrelease-ci/ci/tasks/delete-orphaned-disks-testflight.sh
