name: stannis

instance_groups:
- name: stannis
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: stannis-agent
    release: stannis
  - name: aws_snapshots
    release: stannis
  - name: cf_usage
    release: stannis

properties:
  bosh_uploader:
    bosh_environment: ((bosh_environment))
    bosh_ca_cert: ((bosh_ca_cert))
    bosh_client: ((bosh_client))
    bosh_client_secret: ((bosh_client_secret))
    webserver_api: ((webserver_api))
    webserver_username: ((webserver_username))
    webserver_password: ((webserver_password))
  aws: ~
  aws_snapshots: ~
  cf_usage: ~

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: stannis
  version: 12.1.0
  url: https://github.com/cloudfoundry-community/stannis-boshrelease/releases/download/v12.1.0/stannis-12.1.0.tgz
  sha1: 95c2374b2a64cf5b37b6d032a6dd9392a66ae60e
