meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: bosh_pipeline_dashboard_agent_leader_z1
    templates:
    - name: bosh-pipeline-dashboard-agent
      release: bosh-pipeline-dashboard-agent
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}
  - name: bosh_pipeline_dashboard_agent_z1
    templates:
    - name: bosh-pipeline-dashboard-agent
      release: bosh-pipeline-dashboard-agent
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      bosh_pipeline_dashboard_agent:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
